name: py
on: [push]  
jobs:
      build:
        runs-on: ubuntu-latest
    
        steps:
          - name: checkout repo content
            uses: actions/checkout@v2 # checkout the repository content to github runner.
          - name: setup python
            uses: actions/setup-python@v2
            with:
              python-version: 3.8 #install the python needed
          - name: install lxml
            run: |
              python -m pip install lxml
          - name: install request
            run: |
              python -m pip install requests
          - name: install request
            run: |
              python -m pip install requests
          - name: install bs4
            run: |
              python -m pip install bs4
          - name: List files
            run: |
              ls -R
          - name: install request
            run: |
              python -m pip install requests
          - name: install pandas
            run: |
              python -m pip install pandas
          - name: execute py script # run the run.py to get the latest data
            run: |
              python req.py
          - name: List files 2
            run: |
              ls -R
          - name: Commit and Push
            run: |
             git config --global user.name "github-actions[bot]"
             git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
             git rm data.json
             git add -A
             git commit -m "commit message"
             git push
