name: py
on: [push]  
jobs:
      build:
        runs-on: ubuntu-latest
    
        steps:
          - name: checkout repo content
            uses: actions/checkout@v2 # checkout the repository content to github runner.
          - name: setup python
            uses: actions/setup-python@v2
            with:
              python-version: 3.8 #install the python needed
          - name: install lxml
            run: |
              python -m pip install lxml
          - name: install request
            run: |
              python -m pip install requests
          - name: install request
            run: |
              python -m pip install requests
          - name: install bs4
            run: |
              python -m pip install bs4
          - name: List files
            run: |
              ls -R
          - name: install request
            run: |
              python -m pip install requests
          - name: install pandas
            run: |
              python -m pip install pandas
          - name: install pandas
            run: |
              python annuare.py
          - name: List files 2
            run: |
              ls -R 
          - name: Run the Action
            uses: devops-infra/action-commit-push@master
            with:
               github_token: "${{ secrets.GITHUB_TOKEN }}"
               add_timestamp: true
               commit_prefix: "[AUTO]"
               commit_message: "Automatic commit"
               force: false
               target_branch: update/version
